title: Joël Sango
description: Home
show_downloads: true
url: https://itsjoelsango.github.io
author: Joël
theme: jekyll-theme-cayman

# Add your social links
social:
  github: itsjoelsango
  linkedin: itsjoelsango
  instagram: no_more_on_insta
